---
new_page_extension: html
auto_deploy: false
admin_path: "/_utilities/admin"
webhook_url: 
collections:
- path: _pages/**/*
  label: Pages
  create: all
  default_front_matter_template: default
- path: _utilities/**/*
  label: Utilities
  create: all
- path: _examples/**/*
  label: Examples
  create: all
  default_front_matter_template: default
- path: "/{_posts,_drafts}/**/*"
  label: Posts
  create: all
  default_front_matter_template: default
- path: "/**/*"
  label: Pages
  create: all
  default_front_matter_template: default
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
