---
new_page_extension: html
auto_deploy: false
admin_path: "/_utilities/admin"
webhook_url: 
collections:
- path: _pages
  label: Pages
  create: all
- path: _utilities
  label: Utilities
  create: all
- path: _examples
  label: Examples
  create: all
- path: _posts
  label: Posts
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
